[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "z6Uw5iAzPGjNqXeyDPHUHJJevYAobz6yviPcdqED32L"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/manishroy/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
